apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: oci-ccm
  namespace: kube-system
spec:
  interval: 24h
  url: https://oracle.github.io/oci-cloud-controller-manager
